version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    command:
      - bash -c 'python manage.py migrate  --noinput && python manage.py collectstatic -- noinput && gunicorn config.wsgi:application --log-level debug --timeout
        120 --bind 0.0.0.0:8000 --reload'
    depends_on:
      - postgres


  postgres:
    container_name: db